feat: Allow additional content types to be used by Activity Finder
YCloudYUSA/yusaopeny_activity_finder pull request #28
Opened 2024-02-20 20:20 UTC by froboy

These changes allow Activity Finder to use new location types that are created using the documented process of [Adding additional location types](https://ds-docs.y.org/docs/howto/map-settings-config/#adding-additional-location-types).

AF has previously hardcoded the list of `['branch', 'camp', 'facility']` a number of places and this change aims to remove that hardcoded list in exchange for a more dynamic one. Backwards compatibility is maintained as the default configuration retains that list.

Changes:

- `/admin/openy/settings/activity-finder` gets a new option, **Allowed location types** that uses the logic from Open Y Maps to list any locations that have the required `field_location_coordinates` field.
![SCR-20240220-mruj](https://github.com/YCloudYUSA/yusaopeny_activity_finder/assets/238201/6c15648b-0fac-48ed-a873-909e9f02ef45)
- AF Solr Backend filters on those location types (in addition to any locations passed in as parameters from the url)
- AF4 Block **Exclude by location** field allows filtering from nodes in any of the selected content types
![SCR-20240220-mtxu](https://github.com/YCloudYUSA/yusaopeny_activity_finder/assets/238201/e277d4b6-a0d8-48cc-ad6f-d3526ce1eed6)

This change was done in the scope of work for YMCA of Metro Denver

2024-02-21 08:04 UTC, podarok requested changes
Small validation fixes needed @froboy

2024-02-21 08:04 UTC, podarok commented on src/OpenyActivityFinderSolrBackend.php
> +    $location_types = $this->config->get('location_types');
let's validate if != NULL before using in SQL query below @froboy

2024-02-21 08:04 UTC, podarok commented on src/OpenyActivityFinderSolrBackend.php
> +    $locations = array_map(fn($value): array => [], array_filter($location_types));
same, could be NULL and line 826 below will throw PHP notice

2024-02-21 08:04 UTC, podarok commented on src/Plugin/Block/ActivityFinder4Block.php
> +          'target_bundles' => $location_types,
could be NULL, let's validate before using

2024-02-22 03:27 UTC, froboy commented on src/OpenyActivityFinderSolrBackend.php
> +    $locations = array_map(fn($value): array => [], array_filter($location_types));
Updated.

2024-02-22 03:28 UTC, froboy commented on src/Plugin/Block/ActivityFinder4Block.php
> +          'target_bundles' => $location_types,
This is fixed in 243

2024-02-22 03:29 UTC, froboy commented on src/OpenyActivityFinderSolrBackend.php
> +    $location_types = $this->config->get('location_types');
Fixed

2024-02-22 03:29 UTC, froboy commented
Updated, this is now dependent on https://github.com/open-y-subprojects/openy_map/pull/68

2024-02-22 03:58 UTC, merged

2024-02-22 04:00 UTC, podarok commented
Tagged feature release https://github.com/YCloudYUSA/yusaopeny_activity_finder/releases/tag/4.3.0

Let's ensure it is used by respective distribution release @froboy